import re

SKILL_ONTOLOGY: set[str] = {
    "python", "java", "javascript", "typescript", "c", "c++", "c#",
    "go", "golang", "rust", "kotlin", "swift", "scala", "ruby",
    "php", "perl", "r", "matlab", "julia", "haskell", "elixir",
    "clojure", "dart", "groovy", "bash", "shell scripting", "powershell",
    "assembly", "fortran", "cobol", "lua", "vba", "objective-c",
    "html", "css", "html5", "css3", "sass", "scss", "less",
    "react", "react.js", "reactjs", "angular", "angular.js", "angularjs",
    "vue", "vue.js", "vuejs", "next.js", "nextjs", "nuxt.js", "nuxtjs",
    "svelte", "gatsby", "remix", "jquery", "bootstrap", "tailwind css",
    "tailwindcss", "material ui", "chakra ui", "ant design", "shadcn",
    "redux", "zustand", "mobx", "recoil", "graphql", "rest api",
    "restful api", "soap", "websocket", "webpack", "vite", "babel",
    "eslint", "prettier", "storybook", "jest", "cypress", "playwright",
    "web components", "pwa", "responsive design", "accessibility", "wcag",
    "node.js", "nodejs", "express", "express.js", "fastapi", "django",
    "flask", "spring", "spring boot", "spring framework", "hibernate",
    "rails", "ruby on rails", "laravel", "symfony", "asp.net", ".net",
    ".net core", "grpc", "graphql", "apollo", "microservices",
    "event-driven architecture", "domain-driven design", "ddd",
    "cqrs", "event sourcing", "hexagonal architecture", "clean architecture",
    "machine learning", "deep learning", "artificial intelligence", "ai",
    "ml", "nlp", "natural language processing", "computer vision",
    "tensorflow", "pytorch", "keras", "scikit-learn", "sklearn",
    "xgboost", "lightgbm", "catboost", "hugging face", "transformers",
    "bert", "gpt", "llm", "large language model", "fine-tuning",
    "rag", "retrieval augmented generation", "langchain", "llama",
    "stable diffusion", "opencv", "spacy", "nltk", "gensim",
    "pandas", "numpy", "scipy", "matplotlib", "seaborn", "plotly",
    "data analysis", "data science", "feature engineering",
    "model training", "model deployment", "mlflow", "kubeflow",
    "vertex ai", "sagemaker", "azure ml", "automl",
    "regression", "classification", "clustering", "neural network",
    "cnn", "rnn", "lstm", "attention mechanism", "reinforcement learning",
    "a/b testing", "statistical analysis", "hypothesis testing",
    "time series", "forecasting", "recommendation system",
    "aws", "amazon web services", "azure", "microsoft azure", "gcp",
    "google cloud", "google cloud platform", "digitalocean", "heroku",
    "docker", "kubernetes", "k8s", "helm", "istio", "envoy",
    "terraform", "ansible", "puppet", "chef", "cloudformation",
    "pulumi", "ci/cd", "jenkins", "github actions", "gitlab ci",
    "circle ci", "travis ci", "argocd", "flux", "devops",
    "site reliability engineering", "sre", "platform engineering",
    "infrastructure as code", "iac", "serverless", "lambda",
    "api gateway", "ec2", "s3", "rds", "elasticache",
    "cloudfront", "route 53", "iam", "vpc", "load balancer",
    "nginx", "apache", "caddy", "haproxy", "reverse proxy",
    "monitoring", "observability", "prometheus", "grafana", "datadog",
    "new relic", "splunk", "elk stack", "elasticsearch", "logstash",
    "kibana", "opentelemetry", "jaeger", "zipkin",
    "sql", "mysql", "postgresql", "postgres", "oracle", "sql server",
    "mssql", "sqlite", "mariadb", "mongodb", "mongoose", "redis",
    "memcached", "cassandra", "dynamodb", "firebase", "firestore",
    "supabase", "neo4j", "influxdb", "clickhouse", "snowflake",
    "bigquery", "redshift", "databricks", "spark", "hadoop", "hive",
    "kafka", "rabbitmq", "activemq", "pulsar", "nats",
    "database design", "data modeling", "orm", "query optimization",
    "indexing", "stored procedures", "transactions", "sharding", "replication",
    "cybersecurity", "information security", "penetration testing",
    "ethical hacking", "owasp", "ssl/tls", "authentication",
    "authorization", "oauth", "jwt", "saml", "sso",
    "encryption", "pki", "zero trust", "siem", "soc",
    "vulnerability assessment", "incident response", "compliance",
    "gdpr", "hipaa", "pci dss", "iso 27001", "soc 2",
    "react native", "flutter", "android", "ios", "swift",
    "kotlin", "xamarin", "ionic", "capacitor", "expo",
    "mobile development", "app store", "play store",
    "git", "github", "gitlab", "bitbucket", "version control",
    "jira", "confluence", "trello", "notion", "asana", "linear",
    "slack", "figma", "sketch", "adobe xd", "zeplin",
    "postman", "swagger", "openapi", "insomnia",
    "linux", "unix", "macos", "windows server",
    "vim", "vscode", "intellij", "pycharm",
    "unit testing", "integration testing", "test driven development",
    "tdd", "behavior driven development", "bdd", "end to end testing",
    "code review", "pair programming", "refactoring",
    "design patterns", "solid principles", "dry principle",
    "technical documentation", "api documentation",
    "agile", "scrum", "kanban", "lean", "waterfall", "devops",
    "sprint planning", "retrospective", "standup", "product roadmap",
    "oop", "object oriented programming", "functional programming",
    "asynchronous programming", "concurrent programming",
    "distributed systems", "system design", "scalability",
    "high availability", "fault tolerance", "caching",
    "data pipeline", "etl", "elt", "data warehouse", "data lake",
    "data lakehouse", "airflow", "dbt", "fivetran", "stitch",
    "data quality", "data governance", "metadata management",
    "stream processing", "batch processing",
    "communication", "teamwork", "leadership", "problem solving",
    "critical thinking", "time management", "project management",
    "stakeholder management", "mentoring", "coaching",
    "presentation skills", "technical writing", "documentation",
    "collaboration", "adaptability", "creativity", "initiative",
    "attention to detail", "analytical thinking", "decision making",
    "conflict resolution", "negotiation", "customer focus",
    "cross-functional collaboration", "remote work",
    "fintech", "blockchain", "web3", "smart contracts", "solidity",
    "ethereum", "defi", "nft", "cryptocurrency",
    "healthcare", "ehr", "hl7", "fhir", "telemedicine",
    "e-commerce", "payment gateway", "stripe", "paypal",
    "logistics", "supply chain", "erp", "sap", "salesforce",
    "crm", "marketing automation", "seo", "sem", "google analytics",
    "product management", "ux", "ui", "user research",
    "a11y", "internationalization", "i18n", "localization",
}

CANONICAL_DISPLAY: dict[str, str] = {
    "python": "Python", "java": "Java", "javascript": "JavaScript",
    "typescript": "TypeScript", "c++": "C++", "c#": "C#",
    "go": "Go", "golang": "Go", "rust": "Rust", "kotlin": "Kotlin",
    "swift": "Swift", "scala": "Scala", "ruby": "Ruby", "php": "PHP",
    "r": "R", "matlab": "MATLAB", "julia": "Julia", "lua": "Lua",
    "vba": "VBA", "html": "HTML", "css": "CSS", "html5": "HTML5",
    "css3": "CSS3", "sass": "Sass", "scss": "SCSS",
    "react": "React", "react.js": "React", "reactjs": "React",
    "angular": "Angular", "vue": "Vue.js", "vue.js": "Vue.js",
    "next.js": "Next.js", "nextjs": "Next.js", "nuxt.js": "Nuxt.js",
    "svelte": "Svelte", "jquery": "jQuery", "bootstrap": "Bootstrap",
    "tailwind css": "Tailwind CSS", "tailwindcss": "Tailwind CSS",
    "redux": "Redux", "graphql": "GraphQL", "rest api": "REST API",
    "restful api": "RESTful API", "websocket": "WebSocket",
    "webpack": "Webpack", "vite": "Vite",
    "node.js": "Node.js", "nodejs": "Node.js",
    "express": "Express.js", "express.js": "Express.js",
    "fastapi": "FastAPI", "django": "Django", "flask": "Flask",
    "spring": "Spring", "spring boot": "Spring Boot",
    "rails": "Rails", "laravel": "Laravel",
    "asp.net": "ASP.NET", ".net": ".NET", ".net core": ".NET Core",
    "grpc": "gRPC", "apollo": "Apollo",
    "machine learning": "Machine Learning", "deep learning": "Deep Learning",
    "ai": "AI", "ml": "ML", "nlp": "NLP",
    "natural language processing": "Natural Language Processing",
    "computer vision": "Computer Vision", "tensorflow": "TensorFlow",
    "pytorch": "PyTorch", "keras": "Keras", "scikit-learn": "Scikit-Learn",
    "sklearn": "Scikit-Learn", "xgboost": "XGBoost", "lightgbm": "LightGBM",
    "catboost": "CatBoost", "hugging face": "Hugging Face",
    "transformers": "Transformers", "bert": "BERT", "gpt": "GPT",
    "llm": "LLM", "rag": "RAG", "langchain": "LangChain",
    "opencv": "OpenCV", "spacy": "spaCy", "nltk": "NLTK",
    "pandas": "Pandas", "numpy": "NumPy", "scipy": "SciPy",
    "matplotlib": "Matplotlib", "seaborn": "Seaborn", "plotly": "Plotly",
    "mlflow": "MLflow", "kubeflow": "Kubeflow",
    "vertex ai": "Vertex AI", "sagemaker": "SageMaker", "automl": "AutoML",
    "cnn": "CNN", "rnn": "RNN", "lstm": "LSTM",
    "aws": "AWS", "amazon web services": "AWS", "azure": "Azure",
    "gcp": "GCP", "google cloud": "Google Cloud",
    "digitalocean": "DigitalOcean", "heroku": "Heroku",
    "docker": "Docker", "kubernetes": "Kubernetes", "k8s": "Kubernetes",
    "helm": "Helm", "istio": "Istio", "terraform": "Terraform",
    "ansible": "Ansible", "ci/cd": "CI/CD", "jenkins": "Jenkins",
    "github actions": "GitHub Actions", "gitlab ci": "GitLab CI",
    "argocd": "ArgoCD", "devops": "DevOps", "sre": "SRE",
    "iac": "IaC", "serverless": "Serverless", "lambda": "AWS Lambda",
    "ec2": "EC2", "s3": "S3", "rds": "RDS", "iam": "IAM",
    "vpc": "VPC", "nginx": "Nginx", "apache": "Apache",
    "prometheus": "Prometheus", "grafana": "Grafana", "datadog": "Datadog",
    "elk stack": "ELK Stack", "elasticsearch": "Elasticsearch",
    "opentelemetry": "OpenTelemetry",
    "sql": "SQL", "mysql": "MySQL", "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL", "oracle": "Oracle",
    "sql server": "SQL Server", "mssql": "SQL Server", "sqlite": "SQLite",
    "mariadb": "MariaDB", "mongodb": "MongoDB", "redis": "Redis",
    "cassandra": "Cassandra", "dynamodb": "DynamoDB", "firebase": "Firebase",
    "firestore": "Firestore", "supabase": "Supabase", "neo4j": "Neo4j",
    "influxdb": "InfluxDB", "clickhouse": "ClickHouse", "snowflake": "Snowflake",
    "bigquery": "BigQuery", "redshift": "Redshift", "databricks": "Databricks",
    "spark": "Apache Spark", "hadoop": "Hadoop", "hive": "Hive",
    "kafka": "Apache Kafka", "rabbitmq": "RabbitMQ", "pulsar": "Apache Pulsar",
    "orm": "ORM",
    "owasp": "OWASP", "ssl/tls": "SSL/TLS", "oauth": "OAuth",
    "jwt": "JWT", "saml": "SAML", "sso": "SSO", "pki": "PKI",
    "gdpr": "GDPR", "hipaa": "HIPAA", "pci dss": "PCI DSS",
    "react native": "React Native", "flutter": "Flutter",
    "android": "Android", "ios": "iOS", "xamarin": "Xamarin",
    "ionic": "Ionic", "expo": "Expo",
    "git": "Git", "github": "GitHub", "gitlab": "GitLab",
    "bitbucket": "Bitbucket", "jira": "JIRA", "confluence": "Confluence",
    "figma": "Figma", "sketch": "Sketch", "zeplin": "Zeplin",
    "postman": "Postman", "swagger": "Swagger", "openapi": "OpenAPI",
    "linux": "Linux", "unix": "Unix", "macos": "macOS",
    "vscode": "VS Code", "intellij": "IntelliJ",
    "tdd": "TDD", "bdd": "BDD", "oop": "OOP",
    "solid principles": "SOLID Principles",
    "agile": "Agile", "scrum": "Scrum", "kanban": "Kanban",
    "lean": "Lean", "waterfall": "Waterfall",
    "etl": "ETL", "elt": "ELT", "dbt": "dbt", "airflow": "Apache Airflow",
    "web3": "Web3", "solidity": "Solidity", "ethereum": "Ethereum",
    "defi": "DeFi", "nft": "NFT",
    "ehr": "EHR", "hl7": "HL7", "fhir": "FHIR",
    "erp": "ERP", "sap": "SAP", "salesforce": "Salesforce",
    "crm": "CRM", "seo": "SEO", "sem": "SEM",
    "ux": "UX", "ui": "UI", "a11y": "Accessibility", "i18n": "i18n",
    "ci": "CI/CD", "cd": "CI/CD",
}

SOFT_SKILLS: set[str] = {
    "communication", "teamwork", "leadership", "problem solving",
    "critical thinking", "time management", "project management",
    "stakeholder management", "mentoring", "coaching",
    "presentation skills", "technical writing", "documentation",
    "collaboration", "adaptability", "creativity", "initiative",
    "attention to detail", "analytical thinking", "decision making",
    "conflict resolution", "negotiation", "customer focus",
    "cross-functional collaboration", "remote work",
}


def scan_text_for_skills(text: str) -> list[str]:
    text_lower = text.lower()
    found: dict[str, str] = {}
    sorted_skills = sorted(SKILL_ONTOLOGY, key=len, reverse=True)
    for skill in sorted_skills:
        pattern = r'(?<![a-z0-9\-\+#])' + re.escape(skill) + r'(?![a-z0-9\-\+#])'
        if re.search(pattern, text_lower):
            canonical = CANONICAL_DISPLAY.get(skill, skill.title())
            if canonical not in found:
                found[skill] = canonical
    return sorted(set(found.values()))
